domain: example.com
url: https://example.com
baseurl: "/site"

title: starsandskyforshow
email: yaneevh@gmail.com
author: Neev

lang: en

plugins:
  - jekyll-seo-tag

color: "#999999"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"
